steps:
  # Build the container image
  - name: "gcr.io/cloud-builders/docker"
    args:
      ["build", "-t", "gcr.io/$PROJECT_ID/park-utk-native-api:$COMMIT_SHA", "."]
  # Push the container image to Container Registry
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/park-utk-native-api:$COMMIT_SHA"]
  # Deploy container image to Cloud Run
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      - "run"
      - "deploy"
      - "park-utk-native-api"
      - "--image"
      - "gcr.io/$PROJECT_ID/park-utk-native-api:$COMMIT_SHA"
      - "--region"
      - "us-east1"
options:
  logging: CLOUD_LOGGING_ONLY
images:
  - "gcr.io/$PROJECT_ID/park-utk-native-api:$COMMIT_SHA"
